{
  "description": "sample Glaiveai2K/calculate_distance_d833559f.json",
  "meta": {
    "full_size": 425,
    "stripped_size": 217,
    "features": [],
    "raw_features": [
      "properties",
      "required",
      "type",
      "type:number",
      "type:object"
    ]
  },
  "schema": {
    "properties": {
      "latitude1": {
        "description": "The latitude of the first location",
        "type": "number"
      },
      "latitude2": {
        "description": "The latitude of the second location",
        "type": "number"
      },
      "longitude1": {
        "description": "The longitude of the first location",
        "type": "number"
      },
      "longitude2": {
        "description": "The longitude of the second location",
        "type": "number"
      }
    },
    "required": [
      "latitude1",
      "longitude1",
      "latitude2",
      "longitude2"
    ],
    "type": "object"
  },
  "tests": [
    {
      "description": "llama 70b generated positive",
      "valid": true,
      "data": {
        "latitude1": 40.7128,
        "latitude2": 51.5074,
        "longitude1": -74.006,
        "longitude2": -0.1278
      }
    },
    {
      "description": "llama-70b generated negative",
      "valid": false,
      "rust_error": "\"invalid\" is not of type \"number\"",
      "python_error": "'invalid' is not of type 'number'\n\nFailed validating 'type' in schema['properties']['longitude2']:\n    {'description': 'The longitude of the second location',\n     'type': 'number'}\n\nOn instance['longitude2']:\n    'invalid'",
      "data": {
        "latitude1": 40.7128,
        "longitude1": -74.006,
        "latitude2": 51.5074,
        "longitude2": "invalid"
      }
    }
  ]
}