{
  "description": "sample Glaiveai2K/calculate_distance_9339c7aa.json",
  "meta": {
    "full_size": 381,
    "stripped_size": 173,
    "features": [],
    "raw_features": [
      "properties",
      "required",
      "type",
      "type:number",
      "type:object"
    ]
  },
  "schema": {
    "properties": {
      "lat1": {
        "description": "The latitude of the first location",
        "type": "number"
      },
      "lat2": {
        "description": "The latitude of the second location",
        "type": "number"
      },
      "lon1": {
        "description": "The longitude of the first location",
        "type": "number"
      },
      "lon2": {
        "description": "The longitude of the second location",
        "type": "number"
      }
    },
    "required": [
      "lat1",
      "lon1",
      "lat2",
      "lon2"
    ],
    "type": "object"
  },
  "tests": [
    {
      "description": "llama 70b generated positive",
      "valid": true,
      "data": {
        "lat1": 40.7128,
        "lat2": 34.0522,
        "lon1": -74.006,
        "lon2": -118.2437
      }
    },
    {
      "description": "llama-70b generated negative",
      "valid": false,
      "rust_error": "\"123.456\" is not of type \"number\"",
      "python_error": "'123.456' is not of type 'number'\n\nFailed validating 'type' in schema['properties']['lon2']:\n    {'description': 'The longitude of the second location',\n     'type': 'number'}\n\nOn instance['lon2']:\n    '123.456'",
      "data": {
        "lat1": 40.7128,
        "lon1": -74.006,
        "lat2": 34.0522,
        "lon2": "123.456"
      }
    }
  ]
}